'use client';
import './globals.css'
import { Inter } from 'next/font/google'
import { PageProvider } from '@/context/pageContext'
import Navbar from '@/components/navbar/Navbar'
import Head from "next/head";

const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: '99 Names of Allah',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
  <link rel="stylesheet" type="text/css" charSet="UTF-8" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css" /> 
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css" />
</Head>
      <body className={inter.className}>
        <PageProvider>
          <Navbar />
          {children}
        </PageProvider>
      </body>
    </html>
  )
}
