import Children from '@/components/Children';
import { Inter } from 'next/font/google';
import Head from 'next/head';
import './globals.css';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: '99 Names of Allah',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="google-site-verification" content="sgu7AYl82pjqRA5kxBQyfIoGY_M7uPpMetTozLiySP4" />
      </head>
      <body className={inter.className}>
        <Children children={children} />
      </body>
    </html>
  )
}
