import Hadith from "@/components/hadith/Hadith"
import Hero from "@/components/hero/Hero"
import Names from "@/components/names/Names"

export const metadata = {
  title: '99 Names of Allah',
  description: 'Generated by create next app',
}

export default function Home() {

  return (
    <main>
      <div>
        <Hero />
      </div>

      <div className="bg-black">
        <Hadith />
        <Names />
      </div>

    </main>
  )
}
